name: ci-yoshimura
on:
  push:
    branches: [main]
    paths:
      - 'packages/yoshimura/**'
  pull_request:
    branches: ['*']
    paths:
      - 'packages/yoshimura/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/yoshimura
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
